### ISSUE TITLE
Zig Console not printing "Hello Torizon" message on debug console when trying to debug it on the board

### ISSUE THREAD

**Issue by andreriesco** [toradex/vscode-torizon-templates#162]
When trying to debug a `zigConsole` application on the board (`Torizon ARMv8` debug command), the `Hello Torizon` message is not being printed on VSCode's Debug Console.

![image](https://github.com/toradex/vscode-torizon-templates/assets/83607022/2bec8d7a-ebdc-4c3c-958a-ca6e4d6cb95c)

However, when using `stdout.print()` instead of `log.info` it works.

![image](https://github.com/toradex/vscode-torizon-templates/assets/83607022/54707420-28ca-4437-9b2d-e7754b72a9e2)

P.S. Local debugging (`Local AMD64` debug command) works on both cases.

**Comment by andreriesco** [comment]
@kassane, do you have any ideas on what may be happening?

**Comment by andreriesco** [comment]
@kassane when you have some time, can you take a look on what may be the issue here, please?

**Comment by kassane** [comment]
Hi,

Firstly, `stdout.print` works because it obviously uses stdout (w/ buffer.flush).
```zig
const stdout_file = std.io.getStdOut().writer();
var bw = std.io.bufferedWriter(stdout_file);
const stdout = bw.writer();
try stdout.print("Hello toradex.\n", .{});

try bw.flush();
```

But `std.debug.print` and `std.log.|info|debug|err` uses stderr.

```zig
// works on release mode
pub const std_options = struct {
    pub const log_level = .info;
};
```
Remove this line, because `pub const log_level = .debug` is default.

```zig
// The default log level is based on build mode.
pub const default_level: Level = switch (builtin.mode) {
.Debug => .debug,
.ReleaseSafe => .info,
.ReleaseFast, .ReleaseSmall => .err,
};
```


I had forked an unofficial tutorial on how std.log works, mentioned in the PR.

- [How works `std.log` - whats is the global log level](https://gist.github.com/kassane/a81d1ae2fa2e8c656b91afee8b949426#but-what-is-the-global-log-level)

**Comment by andreriesco** [comment]
Got it. I added [on this commit](https://github.com/toradex/vscode-torizon-templates/commit/a24e6aee9d569105886566e774375afe754ecbcd) the configuration on `launch.json` to print also the `stderr`. Now it is possible to see the output message. Thanks.

**Comment by kassane** [comment]
Amazing!!
