### ISSUE TITLE
C# project: port sharing task fails silently

### ISSUE THREAD

**Issue by etgauth** [toradex/vscode-torizon-templates#43]
I installed WSL2 and Ubuntu 22.04.1 to evaluate our new module using your new VSCode extension. I followed the docs (https://github.com/toradex/torizon-experimental-torizon-ide-v2-docs) but did not see the UAC prompt that should follow the `run-share-wsl-ports` task.

Since there is an accumulation of terminals we don't see it right away that something failed, however a terminal shows:

`/usr/bin/bash: line 1: ifconfig: command not found`

 Found out that ifconfig is not installed in this Ubuntu version. I had to `sudo apt install net-tools` and then re-run the task manually.

**Comment by leograba** [comment]
@microhobby I think `ifconfig` is deprecated in favor of `ip`, even though some distros still allow to install it (e.g. with the `net-tools` package on Debian and Ubuntu). https://www.debian.org/releases/stretch/amd64/release-notes/ch-information.en.html#iproute2

We should consider using `ip` instead, if possible.

**Comment by microhobby** [comment]
@etgauth thank you for reaching out to us. I'm sorry that you're having issues with the extension. Your issue seems to be during initialization of the extension, there is a dependency check during initialization, check the logs in the output tab. 

With that said, your issue is out of the context of this repository. Here we are focusing to the discussion of template development. So I'm going to close this issue and ask you to kindly open a ticket on the Toradex community: https://community.toradex.com/
